title: Tom Humphreys
description: >-
  Incoherent rants about my view of tech things like the cloud, application design, and standards.
baseurl: ""
url: "https://tom01098.github.io"
github_username: Tom01098

theme: minima
plugins:
  - jekyll-feed
